/*
############# CRIAÇÃO DE DOMAINS ################3
*/

-- cria domain e especifica seu tipo e como deve ser checado
-- neste caso tem que ser  maior que 10 chars, se não dá erro
CREATE DOMAIN DMN_NOME
AS VARCHAR(250)
NOT NULL
CHECK (char_length(VALUE) > 10);

-- cria domain e especifica seu tipo e como deve ser checado
CREATE DOMAIN DMN_SIGLA
AS VARCHAR(2)
NOT NULL
CHECK (upper(VALUE) = VALUE);

-- cria domain e especifica seu tipo e como deve ser checado
CREATE DOMAIN DMN_SALARIO
AS FLOAT
NOT NULL
CHECK (VALUE > 0);

-- cria uma tabela usando os domains como tipo de campo
CREATE TABLE clientes02(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome DMN_NOME,
    salario DMN_SALARIO,
    uf DMN_SIGLA
);

-- gera erro no nome que é menor que 10 caracteres
insert into clientes02(nome, salario, uf) values('Filipe', 2.0, 'MG');

-- insere sem problemas
insert into clientes02(nome, salario, uf) values('Filipe Ferreira', 2.0, 'MG');

select * from clientes02;